In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_selection import SelectKBest, f_classif

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report

In [2]:
from ipynb.fs.full.data_loading import get_usable_data

In [3]:
data = get_usable_data()

In [4]:
data.head()

filename  label                                         audio_data  \
0  blues.00000.wav  blues  [0.0073242188, 0.016601562, 0.0076293945, -0.0...   
1  blues.00001.wav  blues  [0.0034179688, 0.0043029785, 0.001373291, 0.00...   
2  blues.00002.wav  blues  [0.019012451, 0.047698975, 0.029418945, -0.018...   
3  blues.00003.wav  blues  [-0.013000488, -0.03060913, -0.036071777, -0.0...   
4  blues.00004.wav  blues  [-0.0063171387, -0.009277344, -0.008331299, -0...   

   audio_sr  chroma_stft_mean  chroma_stft_stdev  chroma_stft_var  rms_mean  \
0     22050          0.350129           0.297946         0.088772  0.130184   
1     22050          0.340849           0.308182         0.094976  0.095908   
2     22050          0.363538           0.291987         0.085257  0.175473   
3     22050          0.404854           0.306592         0.093999  0.141040   
4     22050          0.308526           0.296383         0.087843  0.091501   

   rms_stdev   rms_var  ...  mfccs_17_var  mfccs_18_mean  mfccs_18_stdev  \
0   0.053183  0.002828  ...     36.535866      -0.408730        6.450052   
1   0.048711  0.002373  ...     60.231415       0.296872        6.937811   
2   0.052449  0.002751  ...     47.629646      -1.819024        7.238342   
3   0.079672  0.006348  ...     50.218452       0.636311        6.109478   
4   0.048013  0.002305  ...     75.276741      -0.915952        7.323472   

   mfccs_18_var  mfccs_19_mean  mfccs_19_stdev  mfccs_19_var  mfccs_20_mean  \
0     41.603168      -2.302677        7.419815     55.053650       1.222467   
1     48.133217      -0.282430        7.148847     51.106014       0.530644   
2     52.393597      -3.440458        6.829597     46.643394      -2.238128   
3     37.325726      -0.615968        6.103915     37.257774      -3.405046   
4     53.633236      -4.408018        7.929848     62.882492     -11.704385   

   mfccs_20_stdev  mfccs_20_var  
0        6.851376     46.941349  
1        6.766735     45.788700  
2        5.536529     30.653151  
3        5.653782     31.965254  
4        7.429014     55.190254  

[5 rows x 82 columns]

In [5]:
y = data['label']
X = data.drop(labels=['label', 'filename', 'audio_data', 'audio_sr'],axis=1)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=0)

In [7]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
dt = tree.DecisionTreeClassifier()
dt = dt.fit(X_train, y_train)

In [9]:
y_pred_dt = dt.predict(X_test)
print(accuracy_score(y_test, y_pred_dt))
confusion_matrix(y_test, y_pred_dt)

0.48787878787878786


array([[18,  0,  1,  2,  2,  0,  2,  1,  2,  6],
       [ 0, 17,  3,  0,  0,  4,  0,  0,  0,  0],
       [ 4,  0, 15,  2,  0,  9,  0,  2,  0,  5],
       [ 2,  0,  2,  7,  7,  0,  2,  4,  3,  6],
       [ 4,  0,  0,  1, 19,  0,  3,  6,  3,  1],
       [ 2,  3,  3,  2,  1, 14,  0,  1,  0,  0],
       [ 2,  0,  0,  2,  2,  0, 26,  0,  0,  0],
       [ 0,  0,  1,  5,  6,  0,  0, 17,  3,  1],
       [ 2,  0,  1,  5,  9,  0,  0,  2, 16,  2],
       [ 5,  0,  5,  6,  1,  2,  4,  0,  2, 12]], dtype=int64)

In [10]:
dt_scaled = tree.DecisionTreeClassifier()
dt_scaled = dt_scaled.fit(X_train_scaled, y_train)

In [11]:
y_pred_dt_scaled = dt_scaled.predict(X_test_scaled)
print(accuracy_score(y_test, y_pred_dt_scaled))
confusion_matrix(y_test, y_pred_dt_scaled)

0.47575757575757577


array([[15,  1,  3,  2,  1,  1,  4,  2,  1,  4],
       [ 1, 18,  2,  0,  0,  3,  0,  0,  0,  0],
       [ 4,  2, 15,  4,  0,  4,  0,  1,  2,  5],
       [ 3,  0,  2,  8,  7,  0,  1,  4,  3,  5],
       [ 4,  0,  0,  2, 20,  0,  1,  5,  4,  1],
       [ 1,  4,  3,  0,  1, 15,  0,  2,  0,  0],
       [ 1,  0,  0,  2,  2,  0, 24,  0,  0,  3],
       [ 1,  1,  1,  4,  3,  1,  0, 18,  4,  0],
       [ 1,  0,  1,  4,  7,  0,  0,  4, 14,  6],
       [ 5,  2,  4,  5,  1,  1,  5,  1,  3, 10]], dtype=int64)

In [12]:
rf = RandomForestClassifier(max_depth=2, random_state=0)
rf = rf.fit(X_train, y_train)

In [13]:
y_pred_rf = rf.predict(X_test)
print(accuracy_score(y_test, y_pred_rf))
confusion_matrix(y_test, y_pred_rf)

0.4121212121212121


array([[10,  2,  0,  0,  1,  7, 13,  0,  1,  0],
       [ 0, 24,  0,  0,  0,  0,  0,  0,  0,  0],
       [11,  7,  1,  6,  0,  5,  3,  1,  2,  1],
       [ 0,  0,  1,  9,  3,  0,  6,  8,  6,  0],
       [ 3,  0,  0,  2, 11,  0,  9, 11,  1,  0],
       [ 1, 11,  0,  3,  0,  9,  2,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0, 31,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  2,  1, 26,  3,  0],
       [ 3,  1,  1,  3,  4,  0,  2,  8, 15,  0],
       [ 3,  5,  0,  7,  0,  2, 12,  4,  4,  0]], dtype=int64)

In [14]:
rf_scaled = RandomForestClassifier(max_depth=2, random_state=0)
rf_scaled = rf_scaled.fit(X_train_scaled, y_train)

In [15]:
y_pred_rf_scaled = rf_scaled.predict(X_test_scaled)
print(accuracy_score(y_test, y_pred_rf_scaled))
confusion_matrix(y_test, y_pred_rf_scaled)

0.4121212121212121


array([[10,  2,  0,  0,  1,  7, 13,  0,  1,  0],
       [ 0, 24,  0,  0,  0,  0,  0,  0,  0,  0],
       [11,  7,  1,  6,  0,  5,  3,  1,  2,  1],
       [ 0,  0,  1,  9,  3,  0,  6,  8,  6,  0],
       [ 3,  0,  0,  2, 11,  0,  9, 11,  1,  0],
       [ 1, 11,  0,  3,  0,  9,  2,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0, 31,  0,  0,  0],
       [ 0,  0,  1,  0,  0,  2,  1, 26,  3,  0],
       [ 3,  1,  1,  3,  4,  0,  2,  8, 15,  0],
       [ 3,  5,  0,  7,  0,  2, 12,  4,  4,  0]], dtype=int64)

In [16]:
from sklearn.neural_network import MLPClassifier

In [17]:
mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
mlp.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [18]:
y_pred_mlp = mlp.predict(X_test)
print(accuracy_score(y_test, y_pred_mlp))
confusion_matrix(y_test, y_pred_mlp)

0.11212121212121212


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0, 34],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 24],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 33],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 26],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 32],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 33],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37]], dtype=int64)

In [19]:
mlp_scaled = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
mlp_scaled.fit(X_train_scaled, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [20]:
y_pred_mlp_scaled = mlp_scaled.predict(X_test)
print(accuracy_score(y_test, y_pred_mlp_scaled))
confusion_matrix(y_test, y_pred_mlp_scaled)

0.07272727272727272


array([[ 0, 34,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 24,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 37,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 33,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 37,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 26,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 32,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 33,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 37,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 37,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int64)

In [21]:
mlp2 = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
mlp2.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='sgd')

In [22]:
y_pred_mlp2 = mlp2.predict(X_test)
print(accuracy_score(y_test, y_pred_mlp2))
confusion_matrix(y_test, y_pred_mlp2)

0.11212121212121212


array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0, 34],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 24],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 33],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 26],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 32],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 33],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 37]], dtype=int64)

In [23]:
mlp_scaled2 = MLPClassifier(solver='sgd', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
mlp_scaled2.fit(X_train_scaled, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='sgd')

In [24]:
y_pred_mlp2_scaled = mlp_scaled2.predict(X_test)
print(accuracy_score(y_test, y_pred_mlp2_scaled))
confusion_matrix(y_test, y_pred_mlp2_scaled)

0.09696969696969697


array([[ 0,  0,  0,  0,  0,  0, 34,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 24,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 37,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 33,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 37,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 26,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 32,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 33,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 37,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 37,  0,  0,  0]], dtype=int64)

In [33]:
param_grid = {'activation': ['identity', 'logistic', 'tanh', 'relu'],
                'solver': ['lbgfs', 'sgd', 'adam'],
                'learning_rate': ['constant', 'invscaling', 'adaptive']}  

grid = GridSearchCV(MLPClassifier(), param_grid, refit = True, verbose = 3, n_jobs = 1)

grid.fit(X_train, y_train)

grid_predictions = grid.predict(X_test) 
   
# print classification report 
print(classification_report(y_test, grid_predictions)) 

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV 1/5] END activation=identity, learning_rate=constant, solver=lbgfs;, score=nan total time=   0.0s
[CV 2/5] END activation=identity, learning_rate=constant, solver=lbgfs;, score=nan total time=   0.0s
[CV 3/5] END activation=identity, learning_rate=constant, solver=lbgfs;, score=nan total time=   0.0s
[CV 4/5] END activation=identity, learning_rate=constant, solver=lbgfs;, score=nan total time=   0.0s
[CV 5/5] END activation=identity, learning_rate=constant, solver=lbgfs;, score=nan total time=   0.0s
[CV 1/5] END activation=identity, learning_rate=constant, solver=sgd;, score=0.097 total time=   0.0s
[CV 2/5] END activation=identity, learning_rate=constant, solver=sgd;, score=0.104 total time=   0.0s
[CV 3/5] END activation=identity, learning_rate=constant, solver=sgd;, score=0.090 total time=   0.0s
[CV 4/5] END activation=identity, learning_rate=constant, solver=sgd;, score=0.097 total time=   0.0s
[CV 5/5] END activat